Repository mandusm/aws-modernization-workshop, pull requests merged in 2018-08, with the labels that each got.

#31 Adding Artifactory Module template and sample readme
  _modules.yml
  modules/artifactory/artifactory.json
  modules/artifactory/readme.adoc
  workshops/modernization-august-2018.yml
Labels: lab

#29 Adding the containerize application user guide
  modules/containerize-application/readme.adoc
Labels: lab, module-1

#33 Adding the Fargate Lab Walkthrough
  modules/container-orchestration/petstore-fargate-task-definition.json
  modules/container-orchestration/readme.adoc
Labels: lab

#37 Container Cleanup Fixes
  modules/container-orchestration/petstore-fargate-task-definition.json
  modules/containerize-application/Dockerfile
  modules/containerize-application/docker-compose.yml
  modules/containerize-application/docker-entrypoint.sh
  modules/containerize-application/standalone.xml
Labels: lab

#40 Puccio monitoring module
  modules/containerize-application/readme.adoc
  modules/monitor-application/container/Dockerfile
  modules/monitor-application/container/docker-compose.yml
  modules/monitor-application/readme.adoc
  modules/monitor-application/task-definition/petstore-fargate-task-definition.json
Labels: lab

#47 Docker, Amazon ECS/Fargate Monitoring and Logging Instructions.
  modules/monitor-application/readme.adoc
Labels: lab

#50 Adding CI Module
  _modules.yml
  images/ci-01.png
  images/ci-02.png
  images/ci-03.png
  images/ci-04.png
  images/ci-05.png
  images/ci-06.png
  images/ci-07.png
  images/ci-08.png
  modules/continuous-integration/continuous-integration.yaml
  modules/continuous-integration/readme.adoc
Labels: lab

#56 Task definition example was wrong and some typos in the lab
  modules/container-orchestration/readme.adoc
Labels: lab

#63 Fixing typo in the steps.
  modules/container-orchestration/readme.adoc
Labels: lab

#66 Adding Container Elasticity Module
  _modules.yml
  images/ecs-auto-scaling-console.png
  images/ecs-auto-scaling.png
  images/ecs-services-console.png
  modules/container-elasticity/ca-policy.json
  modules/container-elasticity/cluster-autoscaler.yaml
  modules/container-elasticity/readme.adoc
  modules/container-orchestration/petstore-eks-manifest.yaml
  modules/container-orchestration/readme.adoc
Labels: workshop-iteration

#87 Getting Started Guide Fixes
  images/cloud9-credentials.png
  modules/getting-started/readme.adoc
Labels: bug

#98 Update IAM Instance Profile Order
  modules/getting-started/readme.adoc
Labels: bug
